# Generated by Django 3.0 on 2019-12-18 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioAreaName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioTypeName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioTitle', models.CharField(max_length=256)),
                ('scenarioDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenarioDescription', models.TextField()),
                ('scenarioInitial', models.TextField(blank=True, null=True)),
                ('scenarioFinal', models.TextField(blank=True, null=True)),
                ('scenarioArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanager.ScenarioArea')),
                ('scenarioAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenarioType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanager.ScenarioType')),
            ],
        ),
    ]
