# Generated by Django 3.0 on 2019-12-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanager', '0002_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='scenarioFinal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenarioInitial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
