# Generated by Django 3.0 on 2019-12-18 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testmanager', '0003_auto_20191218_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=256)),
                ('commentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commentScenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanager.Scenario')),
            ],
        ),
    ]
