# Generated by Django 3.0 on 2019-12-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanager', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
