# Generated by Django 3.0 on 2019-12-18 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testmanager', '0005_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=256)),
                ('testCondition', models.TextField(blank=True, null=True)),
                ('testSteps', models.TextField(blank=True, null=True)),
                ('testExpectedResult', models.TextField(blank=True, null=True)),
                ('scenarioDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenarioAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('testScenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanager.Scenario')),
                ('testStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanager.Status')),
            ],
        ),
    ]
