# Generated by Django 3.0 on 2019-12-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmanager', '0006_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='scenarioAuthor',
            new_name='testAuthor',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='scenarioDate',
            new_name='testDate',
        ),
    ]
