# Generated by Django 3.0 on 2019-12-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191214_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media\\default.jpg', upload_to='profile_pics'),
        ),
    ]
