# Generated by Django 3.0 on 2019-12-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191214_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics\\default.jpg', upload_to='profile_pics'),
        ),
    ]
